# Generated by Django 5.2.7 on 2025-10-13 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(30, 'vous avez utuliser la limite des mots autorisés')]),
        ),
        migrations.AlterField(
            model_name='conference',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='ce champs ne doit contenir que des lettres et des espaces ', regex='^[a-zA-Z\\s]+$')]),
        ),
    ]
