# Generated by Django 5.2.7 on 2025-10-16 21:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0002_alter_conference_description_alter_conference_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(30, message='La description doit contenir au moins 30 caractères.')]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='paper',
            field=models.FileField(upload_to='papers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
