# Generated by Django 5.2.7 on 2025-10-13 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SessionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='room',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='ce champ contient que des chiffres et des lettres', regex='^[a-zA-Z0-9]+$')]),
        ),
    ]
